---
apiVersion: v1
kind: Namespace
metadata:
  name: node-density-sm
  labels:
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
{{ if eq .mesh_mode "sidecar" }}
    istio-injection: enabled
{{ end }}
{{ if eq .mesh_mode "ambient" }}
    istio.io/dataplane-mode: ambient
{{ end }}
