---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
indexers:
  - esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}

jobs:
  - name: create-namespaces
    namespace: node-density-sm
    qps: 1
    burst: 1
    jobIterations: 1
    waitWhenFinished: false
    cleanup: true
    jobPause: 10s
    skipIndexing: true
    objects:
      - objectTemplate: namespace.yml
        replicas: 1

  - name: node-density-sm
    namespace: node-density-sm
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    jobPause: 2m
    preLoadImages: true
    preLoadPeriod: 10s
    objects:

      - objectTemplate: pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
