---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
jobs:

  - name: cluster-density-sm
    namespace: cluster-density-sm
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    jobPause: 2m
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      istio-injection: enabled
    objects:

      - objectTemplate: gen-load-cm.yml
        replicas: 2
        inputVars:
          rps: 50

      - objectTemplate: gateway.yml
        replicas: 1
        inputVars:
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: virtualservice.yml
        replicas: 1

      - objectTemplate: service.yml
        replicas: 2
        
      - objectTemplate: route.yml
        replicas: 1
        inputVars:
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: deployment-server.yml
        replicas: 2
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-client.yml
        replicas: 2
        inputVars:
          podReplicas: 2
          ingressDomain: {{.INGRESS_DOMAIN}}

