---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
jobs:

  - name: create-namespaces
    namespace: create-namespaces
    qps: 10
    burst: 10
    jobIterations: {{.JOB_ITERATIONS}}
    waitWhenFinished: false
    cleanup: true
    jobPause: 30s
    skipIndexing: true
    objects:
      - objectTemplate: namespace.yml
        replicas: 1

  - name: cluster-density-sm
    namespace: cluster-density-sm
    jobIterations: {{.JOB_ITERATIONS}}
    qps: 10
    burst: 10
    namespacedIterations: true
    podWait: false
    cleanup: true
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    jobPause: 2m
    objects:

      - objectTemplate: gen-load-cm.yml
        replicas: 2
        inputVars:
          rps: 50

      - objectTemplate: gateway.yml
        replicas: 1
        inputVars:
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: virtualservice.yml
        replicas: 1

      - objectTemplate: service.yml
        replicas: 2
        
      - objectTemplate: route.yml
        replicas: 1
        inputVars:
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: deployment-server.yml
        replicas: 2
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-client.yml
        replicas: 2
        inputVars:
          podReplicas: 2
          ingressDomain: {{.INGRESS_DOMAIN}}

