kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-{{.Replica}}
spec:
  replicas: {{.podReplicas}}
  selector:
    matchLabels:
      name: client-{{.Replica}}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: client-{{.Replica}}
        app: client
    spec:
      topologySpreadConstraints:
      - maxSkew: 1 
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway 
        labelSelector: 
          matchLabels:
            app: client
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
      containers:
      - name: client-app
        image: quay.io/cloud-bulldozer/hloader:latest
        command: ["./load/load.sh"]
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        env:
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        readinessProbe:
          exec:
            command:
            - "/bin/sh"
            - "-c"
            - |
              curl --fail -sS ${SERVICE_ENDPOINT} -o /dev/null || exit 1
              curl --fail -sSk ${ROUTE_ENDPOINT} -o /dev/null || exit 1
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: load
          mountPath: /load
        env:
        - name: ROUTE_ENDPOINT
          value: "https://{{.JobName}}-{{.Iteration}}.{{.ingressDomain}}/128.html"
        - name: SERVICE_ENDPOINT
          value: "http://cluster-density-sm-{{.Replica}}:8080/128.html"
      volumes:
      - name: load
        configMap:
          name: load-{{.JobName}}-{{.Replica}}
          defaultMode: 0750
      restartPolicy: Always
  strategy:
    type: RollingUpdate

