apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: istio-system
  name: {{.JobName}}-{{.Iteration}}
spec:
  port:
    targetPort: http2
  to:
    kind: Service
    name: istio-ingressgateway
  tls:
    termination: edge
  host: {{.JobName}}-{{.Iteration}}.{{.ingressDomain}}
