---
kind: Service
apiVersion: v1
metadata:
  name: {{.JobName}}-{{.Replica}}
spec:
  selector:
    name: server-{{.Replica}}
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
