kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: cd-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{.JobName}}-{{.Iteration}}.{{.ingressDomain}}
