---
kind: Service
apiVersion: v1
metadata:
  name: sm-density-{{.Replica}}
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
